apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: labelName
spec:
  selector:
    matchLabels:
      app: labelName
  template:
    metadata:
      labels: # labels to select/identify the deployment
        app: labelName
    spec:     # pod spec
      containers: 
      - name: frontend
        ports:
        - containerPort: 10
          $patch: delete
        - containerPort: containerPortVal  
        env:
        - name: PORT_VALUE
          value: "containerPortVal"  
        - name: DATABASE_NAME
          value: "databaseName"    
        
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: labelName
spec:
  selector:
    app: labelName
  ports:
    - port: 8080
      $patch: delete
      targetPort: 10
      $patch: delete
    - port: portVal
      targetPort: containerPortVal  


---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: frontend-vs
spec:
  hosts:
  #   - abc.sreyo.in
  #     $patch: delete
    # - def.sreyo.in  
    - domainName
  http:
    - route:
        - destination:
            # host: frontend-service.default.svc.cluster.local
            # $patch: delete
            # host: test-frontend-service.default.svc.cluster.local
            host: serviceName
            port:
              # number: 8081  
              # $patch: delete 
              number: portVal
